### ISSUE TITLE
Not working with pentaho 7.0

### ISSUE THREAD

**Issue by jurodca** [jortilles/byPassPentahoLogin#2]
Hi, I'm trying Pentaho server 7.0 I'm able to do the bypass but it does not allow me to see the OLAP Cube when I call a Saiku Analytics report. Apparently the user of destinations.properties runs out of authentication. I have tried with the admin user, with created users but it does not work. Do you have any idea what I can do? If I log in as admin to the pentaho console and reload the bypass page, the cubes appear, but this is not the behavior that is wanted.

![image](https://user-images.githubusercontent.com/25019042/36392720-96fcb150-157a-11e8-8687-3c50f33703dd.png)

**Comment by jortilles** [comment]
Hi.

In the url in the picture you provided its missing an & betwen saiku and
token. it should be   ...saiku&token=c45... instead of  ...saikutoken=45...
Put the  & on place and it will work,

[image: Imágenes integradas 1]

Juanjo Ortilles - Open Business Analytics
twitter: jortilles
www.jortilles.com / es / cat

2018-02-19 19:41 GMT+01:00 jurodca <notifications@github.com>:

**Comment by jurodca** [comment]
Hi, the url is form by call the bypass http://localhost:8090/pentaho/Urbano?token=fd9cb3f57cdc79830996628c60b42e86&dst=destination_2 for example. I put the missing &, but the OLAP Cubes don't show them.

**Comment by jortilles** [comment]
Look around... it is working actually....


Juanjo Ortilles - Open Business Analytics
twitter: jortilles
www.jortilles.com / es / cat

2018-02-20 14:59 GMT+01:00 jurodca <notifications@github.com>:

**Comment by jurodca** [comment]
The bypass works but the permissions on the registered user in destinations.properties are lost. I have the admin user and does not give access to the cubes. It seems that it recognizes the bypass as anonymous. Is any additional configuration missing? Thanks for your help.

**Comment by jurodca** [comment]
Hi. The problem was caused by an issue with jackrabbit library. I tried in pentaho 8.0 and works fine. Thanks for your advice.
